# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coordinate.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CoordinateSet(object):
    def setupUi(self, CoordinateSet):
        CoordinateSet.setObjectName("CoordinateSet")
        CoordinateSet.resize(392, 123)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CoordinateSet.sizePolicy().hasHeightForWidth())
        CoordinateSet.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(CoordinateSet)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(CoordinateSet)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(CoordinateSet)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(CoordinateSet)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_2.addWidget(self.doubleSpinBox, 1, 0, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(CoordinateSet)
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setMaximum(1000.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_2.addWidget(self.doubleSpinBox_2, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(CoordinateSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(187, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)

        self.retranslateUi(CoordinateSet)
        QtCore.QMetaObject.connectSlotsByName(CoordinateSet)

    def retranslateUi(self, CoordinateSet):
        _translate = QtCore.QCoreApplication.translate
        CoordinateSet.setWindowTitle(_translate("CoordinateSet", "Задайте координату точки "))
        self.label.setText(_translate("CoordinateSet", "Ось X"))
        self.label_2.setText(_translate("CoordinateSet", "Ось Y"))
